### ISSUE TITLE
"fix text results handled as items when using new tables mode" has not been fixed

### ISSUE THREAD

**Issue by maxobremer** [ultrakorne/better-rolltables#117]
This issue wasnt fixed. it still turns text into items (also tested it when it wasjust text without something else in the result, such as a scene, still turns text into items.

![image](https://user-images.githubusercontent.com/86924581/127770169-8f522c3d-9f98-4d0f-81b2-89c78a637dc7.png)

**Comment by Daimakaicho** [comment]
Thanks for your feedback! Damn, I thought I catched it... Can you export your rolltable so I can test it?

**Comment by maxobremer** [comment]
https://we.tl/t-GT5c5hXAoQ
there it is. only an issue when using a better rolltable

**Comment by Daimakaicho** [comment]
![image](https://user-images.githubusercontent.com/1334405/127999508-be81e9a8-5a58-4bf7-b39a-76d249cb632f.png)
Looks like next update will fix this issue 👍

**Comment by Daimakaicho** [comment]
Please update to v1.8.1 and try again. Everything should be fixed.

**Comment by maxobremer** [comment]
so the issue remains if the text has a reference to an item

![image](https://user-images.githubusercontent.com/86924581/128240913-1e60336d-a021-4594-a902-fbe941dd33bc.png)

**Comment by Daimakaicho** [comment]
This is unfortunately a non-supported feature, and I have no idea if it's possible to implement this. I'll need to check deep into foundry's code.
If you really want to have this quickly, you should be able to do it by replacing compendium reference with HTML like this:
```js
<a class="entity-link" data-pack="<id of compendium>" data-entity="<type of object>" data-id="<object it>">
     <i class="fas fa-suitcase"></i> Object name
</a>
```

You can of course put all of this on a single line. Here is an example with Potion of Healing:
```js
<a class="entity-link" data-pack="dnd5e-items" data-entity="Item" data-id="C8AGcvbEDVzgLzYc">
    <i class="fas fa-suitcase"></i> Potion of Healing
</a>
```

**Comment by maxobremer** [comment]
wow very quick respons, dont know exactly what to say except that if you use a default table the issue is not there

![image](https://user-images.githubusercontent.com/86924581/128243731-ae2fa0d1-49c8-4912-8369-731d54e0be25.png)

**Comment by Daimakaicho** [comment]
Default table do parse entity link and display a correct link. Better Rolltable only parse this kinf of reference where there is no other text. Doing what you want to do is not yet supported :(
