### ISSUE TITLE
New Tables reverting back to Default Table Type. 

### ISSUE THREAD

**Issue by tiberius8** [ultrakorne/better-rolltables#76]
Using v1.6.6, and newly created tables will always revert to Default Table Type.

Changing the Result Type also reverts the table to Default Table Type.

**Comment by SlamHammerfist** [comment]
Happening here to.  I can update existing tables to any of the other types without issue, but as soon as I change them to default it will always revert back to default after changing them.  Also the formulas for loot and better tables become blank after clicking update.

**Comment by halfwalk** [comment]
Can confirm here too. Foundry 0.8.6, Better Rolltables 1.6.6.

Clicking "Update" reverts the table to Default Table.

**Comment by ultrakorne** [comment]
will investigate in the evening, thanks for the report

**Comment by ultrakorne** [comment]
this is a tricky one. I will have to investigate more on what is going. Something funky is happening with the preUpdate hook and i m still not sure if its a foundry bug or what

**Comment by halfwalk** [comment]
> this is a tricky one. I will have to investigate more on what is going. Something funky is happening with the preUpdate hook and i m still not sure if its a foundry bug or what

For what it's worth, this appeared in the patch notes for the new version of Foundry that released today (0.8.7):

**"Fixed an issue with the HTML element ID having incorrect values for the RollTableConfig sheet."**

Not sure if that has anything to do with what's going on, but it might be worth checking out.

**Comment by tiberius8** [comment]
Foundry 0.8.7
Better Roll Tables 1.6.7
No other modules are turned on. 

Updated both Foundry and Better Roll Tables to the latest version. No change as updating a table will revert it back to Default Table type.

Also formulas in example tables in compendium such as Encounter Example are blank and don't roll. (trying to document as much as possible)

**Comment by Koreapsu** [comment]
I've pretty much built my campaigns around Better RollTables with some hugely detailed and complicated nested tables.  This issue is massive to me, it effectively makes sessions impossible to run in the format my players are used to.

Thanks a ton for making this addon, and good luck with finding the issue - there's a lot of us hanging out for it.

**Comment by acorpus** [comment]
+1 am experiencing this as well

**Comment by ultrakorne** [comment]
as a temporary workaround you have to click update to save the changes and after the table reverts back to default you can change it back again to the wanted type. After that the change should persist. 

I will have to submit a bug on foundry about this issue (and if its not a bug have to find a new way to do it)

**Comment by ultrakorne** [comment]
@rinnocenti @Koreapsu check this issue for the sub table not rolling https://github.com/ultrakorne/better-rolltables/issues/78
everything seems to work, if not please provide an example of a table not working

**Comment by tiberius8** [comment]
Thanks for the workaround. If anyone experiences tables reverting back to the default type while using the workaround, reloading the application should allow you to use the workaround again.

**Comment by DanielBoettner** [comment]
Related FoundryVTT Bug: https://gitlab.com/foundrynet/foundryvtt/-/issues/5499

If a workaround should be implemented for time being, flags/data would have to be stored on some other entity.

When done [the preUpdateHook function](https://github.com/ultrakorne/better-rolltables/blob/8e7698fb164de570d5b1059847f8c94b114d1c84/scripts/better-table-view.js#L133) and the [Hook](https://github.com/ultrakorne/better-rolltables/blob/8e7698fb164de570d5b1059847f8c94b114d1c84/scripts/brt-main.js#L31) are likely obsolete due to changes in the related [table template ](https://github.com/ultrakorne/better-rolltables/blob/master/templates/select-table-type.hbs) (field now have names that store the value directly to the flag - if changed).

**Comment by mjsuchomel** [comment]
That workaround doesn't work for me, using Foundry v0.8.7 and BRT v1.6.8. I'm testing with the sample "Random NPC" story table. Any modification to the table instantly reverts to "Default Table," clicking Update also reverts it. If I attempt to change it back after Update (per the workaround), then I get an error notification, "Only Journal entries are supported in the story generation as table results." But both entries in the table ARE journal entries. 
![Screenshot 2021-06-24 11-35-31](https://user-images.githubusercontent.com/55298524/123300600-59d7a680-d4e0-11eb-91e6-afa12ec20d9b.png)

**Comment by ultrakorne** [comment]
This could be related to an issue with story table. will create a new bug for the error "Only Journal entries are supported in the story generation as table results."

**Comment by DanielBoettner** [comment]
Don't know if it's worth it (how soon the fix can be merged).

But if anyone is interested to **TEST** the fix you'll find the branch here:
https://github.com/DanielBoettner/better-rolltables/tree/saveTableFix

Feedback is welcome.

The related PR is also linked to this issue.
As mentioned above, this issue was caused by a bug in FoundryVTT that
would drop all the flags saved on a table if they didn't change during an update on the table.

**Comment by DanielBoettner** [comment]
An update to **FoundryVTT 0.8.8** should fix this problem.
The linked branch will be changed to only hold the changes still deemed useful:

- changing document field names to directly save there data into flags
- minor call changes in preparation of FoundryVTT 0.9.0. (deprecation warnings)

I will hold the prepared workaround in a stash. So if for some reason anyone doesn't update to 0.8.8 we can
release a patched 0.8.7 module version later on.

**Comment by illcom94** [comment]
I've updated to 0.8.8 and I still have the issue where if you click Update Table, it reverts back. I can, as a work around, immediately change it back to a Loot Table and it will have kept my previous changes.

**Comment by DanielBoettner** [comment]
@illcom94 I created a fix for that.
But we still have to test it.

For me it now works like a charm. For @ultrakorne it didn't.

I'll test his merge branch and later have a call where we again look at this.

I have high hopes that we can release this very soon.

**Comment by illcom94** [comment]
@DanielBoettner Thank you for taking the time!

**Comment by DanielBoettner** [comment]
People willing to test can test https://github.com/DanielBoettner/better-rolltables/tree/minorImprovmentFlagsSaving branch.

## Good to know before testing
* It is developed and focused **0.8.8**.
* If you still use **0.8.7** and plan to stay on that version please consider upvoting [this issue](https://github.com/DanielBoettner/better-rolltables/issues/2)
* I have the suspicion that there are issues with loading the updated templates/scripts in foundry if the module version didn't change. I did not test this theory yet.

**Comment by Rickyfox** [comment]
Sadly for me the bug appears even in the new version. Is there any helpful information that I can supply you with?

**Comment by DanielBoettner** [comment]
@Rickyfox we released 1.6.12 today.

So first please update. Even though the changes are doing nothing about the issue.

Second please try to open the developer tools (F12) and press `cmd + shift + r` to force a reload without cached data.

Lucky for you, I'm quite flexible currently. So depending on your timezone we can have a chat via discord or zoom. As I would like to no the cause for this.

**Comment by Rickyfox** [comment]
Hey there,
after todays update the issue is resolved for me  - great! Thanks for the quick response :)
